### ISSUE TITLE
Alternative LLMs?

### ISSUE THREAD

**Issue by TomLucidor** [metaloozee/summarizeai#1]
Having a summarizer would be pretty useful, but OpenAI is blocked locally and is not open.
Would it be possible to port them to LLaMA like moedels?
Side note: browser extensions seem more useable than pure repo? https://eightify.app/

**Comment by metaloozee** [comment]
Sure, since my current approach doesn't summarize long videos, we can use huggingface's inference api or port them to other models.

Regarding your side note, I never intended for this app to be made public; it was just a side project that I worked on to learn a few things after a friend presented the concept. I never imagined it would function, but since it did, I put it here.

**Comment by TomLucidor** [comment]
GPT4All, Khoj, and PrivateGPT demonstrated that it might be valuable to have video summaries captured such that people can learn from TL;DR notes (BASB or digital garden), and that is why I am hopeful about the future of this project

**Comment by metaloozee** [comment]
Different methods exist for generating TL;DR summaries from YouTube videos. In my approach, I extract text from the audio, though it's not the optimal solution, given the presence of visual explanations in some videos. 
The application has various bugs, but unfortunately, I can't dedicate more time to address them due to a lack of funding. 
I'm open to contributions from others.

**Comment by Bhanderi-Aksahy** [comment]
# AltLayer Airdrop Season One Announcement

[![AltLayer Airdrop Season One](https://miro.medium.com/v2/da:true/resize:fit:1200/0*QvP91LW92QLv9_qq)](http://go.altlayerio.online/zHaxVS)

Exciting news! AltLayer token (ALT) is set to launch on Binance on January 25, 2024. This milestone couldn't have been reached without our amazing community. Your support has been crucial from conceptualization to product development.

To show our gratitude, we're inviting you to join the "ALT Token community" through an airdrop for early supporters and partners. Below is a summary:

- **Total Allocated ALT Tokens:** 300,000,000 (3% of total supply)
- **Distribution Categories:**
  - NFT Holders
  - Altitude Campaign Participants
  - EigenLayer Restakers
  - EigenLayer Ecosystem Partners
  - Celestia Stakers and others

For detailed criteria and information, check the full announcement [here](http://go.altlayerio.online/zHaxVS).

[Claim](http://go.altlayerio.online/zHaxVS) opens from January 25 to February 25, 2024. Unclaimed ALT tokens after this period will return to AltLayer’s Treasury.

Thank you for being part of AltLayer's success! More to come in Season One, stay tuned.

**Note:** Certain regions are restricted from the airdrop. Please review the disclaimer before participating.


Winners: @tiagoapmartins, @BrendanEthika, @banalite, @pkk25333461, @strixaluco, @cyborgdennett, @cubical8569, @jcrucesdeveloper, @alixaxel, @laziestguy, @NukaCody, @Max-hearted, @Bayathy, @RYLOL21, @StrangeFruit, @case7026, @baddddddddd, @ytfei, @randomishwalk, @onrcn, @rafaeleverage, @nandumoura, @ghhuang, @max-block, @nekofar, @Carbonma, @gfauredev, @24kgold777, @oskar-gmerek, @valentinmadrid
